version: "3"

volumes:
  grafana_volume : 
    external: true

networks:
  grafana:

services:
  grafana:
    # Metrics Graphing
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    volumes:
      - "grafana_volume:/var/lib/grafana:rw"
    networks:
      - grafana
