{
 "title": "GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(dcgm_gpu_utilization)" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(dcgm_mem_copy_utilization)" }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "dcgm_gpu_utilization", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "dcgm_mem_copy_utilization", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "# GPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(dcgm_gpu_temp)" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "dcgm_gpu_temp", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    { "expr": "dcgm_power_usage", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "Framebuffer memory free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "expr": "dcgm_fb_free", "legendFormat": "{{gpu}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 13 },
   "targets": [
    { "expr": "dcgm_gpu_utilization" }
   ]
  }
 ]
}