# 1/3/2019 (FG)
# fgiuste/prometheus:latest
#------------------------------------------------
# Inherits: phusion/baseimage:0.10.2            |
# https://github.com/phusion/baseimage-docker   |
# From Ubuntu 16.04.5                           |
#------------------------------------------------
FROM prom/prometheus:latest

#---------------------------
# Add default prometheus.yml
#---------------------------
ADD prometheus.yml /etc/prometheus/prometheus.yml